java:
  applicationPort: 8080
  image: 'sdshmctspublic.azurecr.io/labs/endakelly:staging-5dfdb47-20220110133919'
  ingressHost: labs-endakelly-{{ .Values.global.environment }}.platform.hmcts.net
  aadIdentityName: labs
  environment:
    FAVOURITE_FRUIT: plum
